name: zulle
favicon: null
layout_spectrum: 0.69055
typography_spectrum: 0.36117
title: zulle
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f9f9'
    - '#212121'
    - '#624f49'
    - '#bcbbc0'
    - '#9d9999'
  brandStrength: 0.7009427535813302
  lightness: 0.28982688300311565
  saturation: 0.17570478399284184
  rhythmicContrast: 0.45865145651623607
purpose: []
